### ISSUE TITLE
Question on midi input library

### ISSUE THREAD

**Issue by OlivierSohn** [krab5/HaskellPortMidi#1]
Hello,

I need midi input in my project (which allows several player to play music connected via the internet), which haskell library would you recommend? Is this one good for this purpose?

Thanks!

EDIT1 : I found this library too : http://hackage.haskell.org/package/PortMidi it's also bindings to portaudio, but embedding the sources of portmidi I think.

**Comment by krab5** [comment]
Hi,

Sorry for the late answer.

Actually this project was more for me to practice Foreign Function Interface; but in the end I think it should be relatively functional (although I saw your issue post).
I think with library ports in Haskell it's always a question of how do you like the types (as most of the time library ports are really just interfaces with the C code).
I designed the high-level structures of this library with my goals in mind; if you find them suiting for yours, then you can give it a shot! :)
If not, there are I think a few MIDI libraries for Haskell (as you pointed out), or you can even do your own port, which is not really that hard (for PortMIDI at least, not in general though).

Also, please note I don't think I will be able to maintain that library much, sorry :(

Anyway, thank you for taking an interest in this!

Hopefully at some point it will be suitable for release...

Bye,
k.

**Comment by OlivierSohn** [comment]
Hello,

I ended up using the other library, and I'm now a maintainer of it!

And thanks for the long response!

Olivier
